# Generated by Django 3.0.3 on 2020-07-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200706_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
